INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Allard', 'Adèle', 'isaac96@example.net', '#mA9jVUxr9', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Huet', 'Sophie', 'rocheaurore@example.net', '$Wd55bSu#n', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Maréchal', 'Stéphane', 'guillotjosephine@example.net', 'Zo7FtzUh(s', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Gautier', 'Frédéric', 'ines94@example.com', '!3MMObcsQa', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Martins', 'André', 'da-silvahenriette@example.com', '(Bx_0HdZs!', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Mercier', 'Lucas', 'jfournier@example.com', ')&UJzE&PS5', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Lambert', 'Lucy', 'maryse57@example.org', '$EMxs3Hp!7', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Riou', 'Zacharie', 'jbarbe@example.org', '!vPqyBfx6W', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Diallo', 'Guillaume', 'manonmarion@example.net', 'Q^JrV8EkK1', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('David', 'Gabrielle', 'ruizsabine@example.net', '&SB2Gqu!*$', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Rodriguez', 'Geneviève', 'nicole97@example.org', '2hBTBGpS_(', 'RESPONSABLE');
INSERT INTO responsable (responsable_id, zone_gestion) VALUES (currval('utilisateur_utilisateur_id_seq'), 'Lacombe-les-Bains');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Laporte', 'Nathalie', 'delannoygregoire@example.org', '3CoOQkjm*J', 'TECHNICIEN');
INSERT INTO technicien (technicien_id, specialite) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ENTRETIEN');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Delahaye', 'Charles', 'stephane17@example.com', 'U_1AxIYcX%', 'TECHNICIEN');
INSERT INTO technicien (technicien_id, specialite) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ENTRETIEN');
