INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Duval', 'René', 'ksauvage@example.org', '71if2Ov@8#', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Mace', 'Camille', 'mletellier@example.org', '%72TFeslI#', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Lenoir', 'Robert', 'philippeteixeira@example.com', '9$2^rQtlU)', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Gilles', 'Hugues', 'srobert@example.org', 'Kh3Bf_BN(7', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Labbé', 'Corinne', 'xgoncalves@example.net', 'Wu_0OUcXs&', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Cohen', 'Brigitte', 'antoineleveque@example.org', 'X%O^3DAzgA', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('François', 'Madeleine', 'wferreira@example.com', '@bF@B4!ki0', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'MENSUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Girard', 'Marcel', 'jdeschamps@example.org', '4uvJ&SNg)2', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Berthelot', 'Alexandre', 'lemoinestephanie@example.com', '!B3LpTfizj', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Costa', 'Adèle', 'marinmarine@example.org', 'q8YuC*7n@k', 'CLIENT');
INSERT INTO client (client_id, abonnement) VALUES (currval('utilisateur_utilisateur_id_seq'), 'ANNUEL');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Jean', 'Bernadette', 'gaudinjerome@example.net', '%Ov@#W#xq3', 'RESPONSABLE');
INSERT INTO responsable (responsable_id, zone_gestion) VALUES (currval('utilisateur_utilisateur_id_seq'), 'Lebreton');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Maurice', 'Michelle', 'nicole34@example.org', '8X*LrsaW^p', 'TECHNICIEN');
INSERT INTO technicien (technicien_id, specialite) VALUES (currval('utilisateur_utilisateur_id_seq'), 'REPARATION');
INSERT INTO utilisateur (nom, prenom, email, mot_de_passe, type_utilisateur) VALUES ('Muller', 'Benjamin', 'dguillaume@example.net', 'N5TnwIhT+f', 'TECHNICIEN');
INSERT INTO technicien (technicien_id, specialite) VALUES (currval('utilisateur_utilisateur_id_seq'), 'INSPECTION');
